DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS order_rows;

DROP SEQUENCE IF EXISTS seq1;
DROP SEQUENCE IF EXISTS num;

CREATE SEQUENCE seq1 START WITH 1;
CREATE SEQUENCE num START WITH 1001;

CREATE TABLE orders (
   id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq1'),
   name VARCHAR(255),
   number VARCHAR(255) DEFAULT concat('OR-', nextval('num'))
);

CREATE TABLE order_rows (
   order_id BIGINT NOT NULL,
   item_name VARCHAR(255),
   price int
);
